version: '3.8'

services:
  db:
    image: postgres:14.5
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      start_period: 2s
      interval: 5s
      timeout: 1s
      retries: 5
    networks:
      - backend

  migrations:
    build:
      context: migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./migrations:/migrations
    command: >
      sqlx migrate run
    networks:
      - backend

  dummy_data_loader:
    image: postgres:14.5
    volumes:
      - ./local:/local
    depends_on:
      - migrations
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: >
      bash -c "psql $$DATABASE_URL < /local/dummy_data.sql"
    networks:
      - backend

networks:
  backend:
