version: '3.8'

services:
  db:
    image: postgres:14.5
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DB_HOST=db
      - DB_PORT=5432
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  migrations:
    build:
      context: migrations
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./migrations:/migrations

  dummy_data_loader:
    image: postgres:14.5
    volumes:
      - ./development:/development
    depends_on:
      - migrations
    command: >
      bash -c "psql $$DATABASE_URL < /development/dummy_data.sql"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres